import type { PolymarketEvent } from '../types';

// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/update_markets.cjs
// Last updated: 2026-02-18T11:24:34.574Z

export const MOCK_EVENTS: PolymarketEvent[] = [
  {
    "id": "mock-1",
    "title": "Democratic Presidential Nominee 2028",
    "slug": "democratic-presidential-nominee-2028",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/democrats+2028+donkey.png",
    "markets": [
      {
        "id": "m1",
        "question": "Will Stephen A. Smith win the 2028 Democratic presidential nomination?",
        "slug": "democratic-presidential-nominee-2028",
        "outcomePrices": [
          "0.0125",
          "0.9875"
        ],
        "volume": 676639697.488858,
        "liquidity": 36372670.49802,
        "active": true,
        "closed": false
      }
    ],
    "volume": 676639697.488858,
    "liquidity": 36372670.49802,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-2",
    "title": "Who will Trump nominate as Fed Chair?",
    "slug": "who-will-trump-nominate-as-fed-chair",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/who-will-trump-nominate-as-fed-chair-9p19ttRwsbKL.png",
    "markets": [
      {
        "id": "m2",
        "question": "Will Trump nominate Kevin Warsh as the next Fed chair?",
        "slug": "who-will-trump-nominate-as-fed-chair",
        "outcomePrices": [
          "0.943",
          "0.057"
        ],
        "volume": 492310944.56466,
        "liquidity": 67788739.03503,
        "active": true,
        "closed": false
      }
    ],
    "volume": 492310944.56466,
    "liquidity": 67788739.03503,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-3",
    "title": "Republican Presidential Nominee 2028",
    "slug": "republican-presidential-nominee-2028",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/republicans+2028.png",
    "markets": [
      {
        "id": "m3",
        "question": "Will Donald Trump win the 2028 Republican presidential nomination?",
        "slug": "republican-presidential-nominee-2028",
        "outcomePrices": [
          "0.0405",
          "0.9595"
        ],
        "volume": 305394662.144452,
        "liquidity": 16047441.30782,
        "active": true,
        "closed": false
      }
    ],
    "volume": 305394662.144452,
    "liquidity": 16047441.30782,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-4",
    "title": "Presidential Election Winner 2028",
    "slug": "presidential-election-winner-2028",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/presidential-election-winner-2024-afdda358-219d-448a-abb5-ba4d14118d71.png",
    "markets": [
      {
        "id": "m4",
        "question": "Will JD Vance win the 2028 US Presidential Election?",
        "slug": "presidential-election-winner-2028",
        "outcomePrices": [
          "0.2455",
          "0.7545"
        ],
        "volume": 300188808.801997,
        "liquidity": 21647797.36346,
        "active": true,
        "closed": false
      }
    ],
    "volume": 300188808.801997,
    "liquidity": 21647797.36346,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-5",
    "title": "US strikes Iran by...?",
    "slug": "us-strikes-iran-by",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/us-strikes-iran-by-october-3-2sVnIHq3sjqF.jpg",
    "markets": [
      {
        "id": "m5",
        "question": "US strikes Iran by February 5, 2026?",
        "slug": "us-strikes-iran-by",
        "outcomePrices": [
          "0",
          "1"
        ],
        "volume": 284645927.395142,
        "liquidity": 1343001.05201,
        "active": true,
        "closed": false
      }
    ],
    "volume": 284645927.395142,
    "liquidity": 1343001.05201,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-6",
    "title": "2026 NBA Champion",
    "slug": "2026-nba-champion",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/nba-finals-points-leader-7g2ZEZvMXxLb.jpg",
    "markets": [
      {
        "id": "m6",
        "question": "Will the Oklahoma City Thunder win the 2026 NBA Finals?",
        "slug": "2026-nba-champion",
        "outcomePrices": [
          "0.355",
          "0.645"
        ],
        "volume": 263595317.948697,
        "liquidity": 16397053.23694,
        "active": true,
        "closed": false
      }
    ],
    "volume": 263595317.948697,
    "liquidity": 16397053.23694,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-7",
    "title": "English Premier League Winner ",
    "slug": "english-premier-league-winner",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/english-premier-league-winner-VFcNkpZeA9Sz.jpg",
    "markets": [
      {
        "id": "m7",
        "question": "Will Brentford win the 2025–26 English Premier League?",
        "slug": "english-premier-league-winner",
        "outcomePrices": [
          "0.0015",
          "0.9985"
        ],
        "volume": 236444681.634467,
        "liquidity": 15694952.93447,
        "active": true,
        "closed": false
      }
    ],
    "volume": 236444681.634467,
    "liquidity": 15694952.93447,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-8",
    "title": "UEFA Champions League Winner ",
    "slug": "uefa-champions-league-winner",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/uefa-champions-league-2025-26-which-teams-qualify-StbSIjaEx2St.png",
    "markets": [
      {
        "id": "m8",
        "question": "Will Real Madrid win the 2025–26 Champions League?",
        "slug": "uefa-champions-league-winner",
        "outcomePrices": [
          "0.095",
          "0.905"
        ],
        "volume": 227573804.809335,
        "liquidity": 6510478.45697,
        "active": true,
        "closed": false
      }
    ],
    "volume": 227573804.809335,
    "liquidity": 6510478.45697,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-9",
    "title": "2026 FIFA World Cup Winner ",
    "slug": "2026-fifa-world-cup-winner-595",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/2026-fifa-world-cup-winner-595-8rgoVIZnbKgL.png",
    "markets": [
      {
        "id": "m9",
        "question": "Will Spain win the 2026 FIFA World Cup?",
        "slug": "2026-fifa-world-cup-winner-595",
        "outcomePrices": [
          "0.165",
          "0.835"
        ],
        "volume": 160129099.457722,
        "liquidity": 25612995.10264,
        "active": true,
        "closed": false
      }
    ],
    "volume": 160129099.457722,
    "liquidity": 25612995.10264,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-10",
    "title": "Fed decision in March?",
    "slug": "fed-decision-in-march-885",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/jerome+powell+glasses1.png",
    "markets": [
      {
        "id": "m10",
        "question": "Will the Fed decrease interest rates by 50+ bps after the March 2026 meeting?",
        "slug": "fed-decision-in-march-885",
        "outcomePrices": [
          "0.0075",
          "0.9925"
        ],
        "volume": 133613939.168582,
        "liquidity": 6064355.24252,
        "active": true,
        "closed": false
      }
    ],
    "volume": 133613939.168582,
    "liquidity": 6064355.24252,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-11",
    "title": "La Liga Winner ",
    "slug": "la-liga-winner-114",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/la-liga-winner-885-D1lKS37jyqsm.png",
    "markets": [
      {
        "id": "m11",
        "question": "Will Celta Vigo win the 2025–26 La Liga?",
        "slug": "la-liga-winner-114",
        "outcomePrices": [
          "0.0015",
          "0.9985"
        ],
        "volume": 89768307.196906,
        "liquidity": 7240958.92893,
        "active": true,
        "closed": false
      }
    ],
    "volume": 89768307.196906,
    "liquidity": 7240958.92893,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-12",
    "title": "What price will Bitcoin hit in February?",
    "slug": "what-price-will-bitcoin-hit-in-february-2026",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
    "markets": [
      {
        "id": "m12",
        "question": "Will Bitcoin reach $150,000 in February?",
        "slug": "what-price-will-bitcoin-hit-in-february-2026",
        "outcomePrices": [
          "0.0025",
          "0.9975"
        ],
        "volume": 73067243.034703,
        "liquidity": 5610762.74578,
        "active": true,
        "closed": false
      }
    ],
    "volume": 73067243.034703,
    "liquidity": 5610762.74578,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-13",
    "title": "Which coalition will form the next Dutch government?",
    "slug": "which-coalition-will-form-the-next-dutch-government",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/which-coalition-will-form-the-next-german-government-196-KDmVJweIjYaA.jpg",
    "markets": [
      {
        "id": "m13",
        "question": "Will the next Dutch government be PVV + JA21?",
        "slug": "which-coalition-will-form-the-next-dutch-government",
        "outcomePrices": [
          "0.0005",
          "0.9995"
        ],
        "volume": 59119674.920332,
        "liquidity": 1357725.55032,
        "active": true,
        "closed": false
      }
    ],
    "volume": 59119674.920332,
    "liquidity": 1357725.55032,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-14",
    "title": "Venezuela leader end of 2026?",
    "slug": "venezuela-leader-end-of-2026",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/venezuela-leader-end-of-2026-lOfqbUxiKAsg.png",
    "markets": [
      {
        "id": "m14",
        "question": "Will María Corina Machado be the leader of Venezuela end of 2026?",
        "slug": "venezuela-leader-end-of-2026",
        "outcomePrices": [
          "0.1",
          "0.9"
        ],
        "volume": 45028058.34266,
        "liquidity": 925257.35665,
        "active": true,
        "closed": false
      }
    ],
    "volume": 45028058.34266,
    "liquidity": 925257.35665,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-15",
    "title": "NBA MVP ",
    "slug": "nba-mvp-694",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/nba-mvp-694-FG0ToWV-YK16.jpg",
    "markets": [
      {
        "id": "m15",
        "question": "Will Trae Young win the 2025–2026 NBA MVP?",
        "slug": "nba-mvp-694",
        "outcomePrices": [
          "0.0005",
          "0.9995"
        ],
        "volume": 34133626.301,
        "liquidity": 1556833.07855,
        "active": true,
        "closed": false
      }
    ],
    "volume": 34133626.301,
    "liquidity": 1556833.07855,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-16",
    "title": "US next strikes Iran on...?",
    "slug": "us-next-strikes-iran-on-843",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/us-strikes-iran-next-on-i8O7r2SBkycN.jpg",
    "markets": [
      {
        "id": "m16",
        "question": "Will the US next strike Iran in January 2026 (ET)?",
        "slug": "us-next-strikes-iran-on-843",
        "outcomePrices": [
          "0",
          "1"
        ],
        "volume": 31375713.983496,
        "liquidity": 654569.68002,
        "active": true,
        "closed": false
      }
    ],
    "volume": 31375713.983496,
    "liquidity": 654569.68002,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-17",
    "title": "2026 NHL Stanley Cup Champion ",
    "slug": "2026-nhl-stanley-cup-champion",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/stanley-cup-champion-2026-05M0VRODAaEb.jpg",
    "markets": [
      {
        "id": "m17",
        "question": "Will the Carolina Hurricanes win the 2026 NHL Stanley Cup?",
        "slug": "2026-nhl-stanley-cup-champion",
        "outcomePrices": [
          "0.105",
          "0.895"
        ],
        "volume": 30542963.661184,
        "liquidity": 3090727.7357,
        "active": true,
        "closed": false
      }
    ],
    "volume": 30542963.661184,
    "liquidity": 3090727.7357,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-18",
    "title": "New \"Stranger Things\" episode released by...? ",
    "slug": "new-stranger-things-episode-released-by-wednesday",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/new-stranger-things-episode-released-by-wednesday-4NShFZwCps4u.jpg",
    "markets": [
      {
        "id": "m18",
        "question": "New \"Stranger Things\" episode released by Wednesday? ",
        "slug": "new-stranger-things-episode-released-by-wednesday",
        "outcomePrices": [
          "0",
          "1"
        ],
        "volume": 28503679.446403,
        "liquidity": 252707.86123,
        "active": true,
        "closed": false
      }
    ],
    "volume": 28503679.446403,
    "liquidity": 252707.86123,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-19",
    "title": "Will Trump acquire Greenland before 2027?",
    "slug": "will-trump-acquire-greenland-before-2027",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/will-trump-acquire-greenland-in-2025-5ZDkcIGhdBMW.jpg",
    "markets": [
      {
        "id": "m19",
        "question": "Will Trump acquire Greenland before 2027?",
        "slug": "will-trump-acquire-greenland-before-2027",
        "outcomePrices": [
          "0.115",
          "0.885"
        ],
        "volume": 28036644.442353,
        "liquidity": 672215.7073,
        "active": true,
        "closed": false
      }
    ],
    "volume": 28036644.442353,
    "liquidity": 672215.7073,
    "active": true,
    "closed": false
  },
  {
    "id": "mock-20",
    "title": "2026 Men's Australian Open Winner",
    "slug": "2026-mens-australian-open-winner",
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/2026-mens-australian-open-winner-0qYpn3OBLJPP.png",
    "markets": [
      {
        "id": "m20",
        "question": "Will Jack Draper win the 2026 Australian Open?",
        "slug": "2026-mens-australian-open-winner",
        "outcomePrices": [
          "0",
          "1"
        ],
        "volume": 27364597.254852,
        "liquidity": 2080622.81007,
        "active": true,
        "closed": false
      }
    ],
    "volume": 27364597.254852,
    "liquidity": 2080622.81007,
    "active": true,
    "closed": false
  }
];
